[package]
name = "log-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.115"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
axum = "0.7.5"
tokio-stream = "0.1"

